### ISSUE TITLE
Unable to Load Distributed Tracing Blade

### ISSUE THREAD

**Issue by 1openwindow** [Azure/Azure-Spring-Cloud#1] opened 2019-10-24 03:08 UTC
**Describe the bug**
Unable to Load Distributed Tracing Blade

![unabletoload](https://user-images.githubusercontent.com/26411726/67449927-668e6200-f64e-11e9-85a1-c88ed47b4e61.png)

**To Reproduce**
don't know to reproduce it.

**Comment by xscript** [comment] 2019-10-30 14:53
Duplicate of #6

**Closed by xscript** 2019-10-30 14:53 UTC
Labels: bug
